name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_URL: ${{ secrets.HF_SPACE_URL }}
        run: |
          git lfs uninstall
          git config lfs.allowincompletepush true
          GIT_LFS_SKIP_PUSH=1 git push --force https://jacksonsantosjr:$HF_TOKEN@$HF_SPACE_URL main
